"""Created database table for the checkin

Revision ID: 810b57ceb44e
Revises: cd8add754792
Create Date: 2025-08-12 11:42:34.146218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810b57ceb44e'
down_revision: Union[str, Sequence[str], None] = 'cd8add754792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_type', sa.String(length=20), nullable=False),
    sa.Column('sleep_quality', sa.String(length=100), nullable=True),
    sa.Column('body_sensation', sa.String(length=100), nullable=True),
    sa.Column('energy_level', sa.String(length=100), nullable=True),
    sa.Column('mental_state', sa.String(length=100), nullable=True),
    sa.Column('executive_task', sa.String(length=100), nullable=True),
    sa.Column('emotion_category', sa.String(length=100), nullable=True),
    sa.Column('overwhelm_amount', sa.String(length=100), nullable=True),
    sa.Column('emotion_in_moment', sa.String(length=100), nullable=True),
    sa.Column('surroundings_impact', sa.String(length=100), nullable=True),
    sa.Column('meaningful_moments_quantity', sa.String(length=100), nullable=True),
    sa.Column('checkin_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    # ### end Alembic commands ###
