"""Updated gender column to have 3 values

Revision ID: cd8add754792
Revises: 384e3632e6e3
Create Date: 2025-08-12 10:33:37.821455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8add754792'
down_revision: Union[str, Sequence[str], None] = '384e3632e6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update existing string values to integers
    op.execute("UPDATE users SET gender = CASE WHEN gender = 'Male' THEN 0 WHEN gender = 'Female' THEN 1 WHEN gender = 'Third gender' THEN 2 ELSE NULL END")
    
    # Then alter the column type with USING clause
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="gender::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
